/**
 * ============================================================================
 * Lesson 9: Debugging CKB Scripts
 * ============================================================================
 *
 * This module walks through the debugging methodology for CKB on-chain scripts.
 * Since CKB scripts run inside a deterministic RISC-V virtual machine with no
 * network access, no filesystem, and no standard I/O, debugging them requires
 * specialized tools and techniques.
 *
 * What you will learn:
 *   1. The most common CKB script error codes and what they mean
 *   2. A systematic debugging methodology for CKB scripts
 *   3. How to use CKB-Debugger to run scripts offline
 *   4. How to read error output from failed transactions
 *   5. How to add debug prints using the ckb_debug! macro
 *   6. How to interpret VM exit codes vs script-defined error codes
 *
 * Key Concepts:
 *   - CKB scripts return an i8 exit code: 0 = success, non-zero = failure
 *   - The CKB VM (ckb-vm) itself can also produce errors (negative codes)
 *   - CKB-Debugger lets you run scripts locally with mock transactions
 *   - The ckb_debug! macro writes to stderr when run under the debugger
 *   - Determinism means the same inputs always produce the same output
 *
 * Prerequisites:
 *   - Completion of Lesson 7 (Script Basics) and Lesson 8 (Hash Lock Script)
 *   - Familiarity with CKB transaction structure
 *   - Rust toolchain (for understanding the script source code)
 *
 * Run with:
 *   npx tsx src/index.ts
 *
 * ============================================================================
 */

// ============================================================================
// Section 1: CKB Script Error Codes Overview
// ============================================================================

/**
 * CKB has two layers of error codes:
 *
 * 1. VM-Level Errors (negative numbers):
 *    These come from the CKB-VM itself and indicate problems with the script
 *    binary or execution environment, not with your script's logic.
 *
 * 2. Script-Level Errors (positive numbers):
 *    These are returned by your script code via the exit code (i8 return value).
 *    You define what each code means in your script.
 *
 * When a transaction fails validation, the CKB node reports which script failed
 * and what exit code it returned. Understanding these codes is the first step
 * in debugging.
 */

/**
 * VM-level error codes returned by CKB-VM.
 * These are always negative and indicate infrastructure-level problems.
 */
const VM_ERRORS: Record<number, { name: string; description: string; commonCauses: string[] }> = {
  [-1]: {
    name: "INDEX_OUT_OF_BOUND",
    description: "A syscall tried to access an index that does not exist.",
    commonCauses: [
      "Loading a witness at an index where no witness exists",
      "Loading a cell_dep at an index beyond the available deps",
      "Loading an input/output at an index beyond the transaction's inputs/outputs",
      "Off-by-one errors in loop counters when iterating over inputs",
    ],
  },
  [-2]: {
    name: "ITEM_MISSING",
    description: "The requested item exists at the index but the specific field is missing.",
    commonCauses: [
      "Trying to load the type script of a cell that has no type script",
      "Requesting cell data when the cell exists but has empty data",
      "Accessing optional fields that were not set in the transaction",
    ],
  },
  [-3]: {
    name: "SLICE_OUT_OF_BOUND",
    description: "Attempted to read a slice of data beyond the available bytes.",
    commonCauses: [
      "Specifying an offset + length that exceeds the data size in a partial load syscall",
      "Reading more bytes from a witness than it actually contains",
      "Incorrect buffer size calculations when using low-level syscalls",
    ],
  },
  [-4]: {
    name: "WRONG_FORMAT",
    description: "Data could not be parsed in the expected format.",
    commonCauses: [
      "Witness data is not valid molecule-encoded WitnessArgs",
      "Script args contain unexpected data layout",
      "Deserialization failed because the data was generated by a different version",
    ],
  },
  [-5]: {
    name: "UNKNOWN_SYSCALL",
    description: "The script called a syscall number that CKB-VM does not recognize.",
    commonCauses: [
      "Script was compiled for a different CKB version with newer syscalls",
      "Corrupted binary or wrong compilation target",
      "Using a syscall that was removed or renumbered between CKB versions",
    ],
  },
};

/**
 * Common script-level error codes used by well-known CKB scripts.
 * Your own scripts can define any positive error codes you like, but these
 * are conventions from the CKB ecosystem.
 */
const WELL_KNOWN_SCRIPT_ERRORS: Record<number, { script: string; name: string; description: string }> = {
  [1]: {
    script: "secp256k1-blake160",
    name: "ERROR_ARGUMENTS_LEN",
    description: "Script args length is not exactly 20 bytes (blake160 hash).",
  },
  [2]: {
    script: "secp256k1-blake160",
    name: "ERROR_ENCODING",
    description: "Witness could not be decoded as WitnessArgs molecule structure.",
  },
  [3]: {
    script: "secp256k1-blake160",
    name: "ERROR_WITNESS_SIZE",
    description: "WitnessArgs lock field is not exactly 65 bytes (secp256k1 signature).",
  },
  [4]: {
    script: "secp256k1-blake160",
    name: "ERROR_PUBKEY_BLAKE160_HASH",
    description: "Recovered public key hash does not match the expected blake160 in args.",
  },
  [5]: {
    script: "secp256k1-blake160",
    name: "ERROR_VERIFICATION",
    description: "Signature verification failed — signature is invalid for the message.",
  },
};

// ============================================================================
// Section 2: Debugging Methodology
// ============================================================================

/**
 * A systematic approach to debugging CKB scripts:
 *
 * Step 1: READ THE ERROR
 *   - The CKB node or SDK will report which script failed and its exit code.
 *   - Identify whether it is a VM error (negative) or script error (positive).
 *   - Check the error against known codes (see the tables above).
 *
 * Step 2: REPRODUCE LOCALLY
 *   - Dump the failing transaction to a JSON file.
 *   - Use CKB-Debugger to run the script offline with the same inputs.
 *   - This gives you full control and faster iteration.
 *
 * Step 3: ADD DEBUG PRINTS
 *   - Insert ckb_debug!() calls at key points in your Rust script.
 *   - Recompile and run under CKB-Debugger to see the debug output.
 *   - Trace the execution path to find where it diverges from expectations.
 *
 * Step 4: ISOLATE THE BUG
 *   - Once you know the failing code path, examine each operation.
 *   - Common pitfalls: wrong indices, incorrect lengths, missing error returns.
 *   - Check your assumptions about data layout and encoding.
 *
 * Step 5: FIX AND VERIFY
 *   - Apply the fix and run under CKB-Debugger again.
 *   - Test both the happy path (should succeed) and error paths (should fail).
 *   - Deploy the fixed script and verify on testnet.
 */

// ============================================================================
// Section 3: CKB-Debugger Usage
// ============================================================================

/**
 * CKB-Debugger is a command-line tool for running CKB scripts locally.
 * It simulates the CKB-VM environment with a mock transaction, allowing you
 * to test and debug scripts without deploying to a real chain.
 *
 * Installation:
 *   cargo install ckb-debugger
 *
 * Or download a prebuilt binary from:
 *   https://github.com/nervosnetwork/ckb-standalone-debugger/releases
 */

/**
 * Demonstrates the CKB-Debugger commands and flags that are most useful
 * for debugging scripts.
 */
function printDebuggerUsage(): void {
  console.log(`
  =====================================================================
  CKB-Debugger: Command Reference
  =====================================================================

  Basic usage:
    ckb-debugger --tx-file <tx.json> --script-group-type lock --cell-index 0

  Key flags:
    --tx-file <path>         Path to the transaction JSON file to execute.
                             This file contains the full transaction with
                             all inputs, outputs, witnesses, and cell deps.

    --script-group-type      Which script type to run:
        lock                   Run the lock script
        type                   Run the type script

    --cell-index <N>         Which input cell's script to execute (0-based).
                             For lock scripts, this determines which input's
                             lock script gets verified.

    --cell-type <path>       Path to the compiled script binary (.debug or
                             release). Overrides the script in the transaction
                             for testing a local build.

    --bin <path>             Directly run a script binary against the mock
                             transaction, without looking up the script
                             from cell deps.

    --max-cycles <N>         Maximum number of VM cycles to allow.
                             Default is usually sufficient for testing.
                             Set higher for complex scripts.

    --enable-debug           Enable ckb_debug! output. Debug messages will
                             be printed to stderr.

  Examples:

    # Run a lock script from a transaction file
    ckb-debugger \\
      --tx-file tx.json \\
      --script-group-type lock \\
      --cell-index 0

    # Run with a local debug build of the script (faster iteration)
    ckb-debugger \\
      --tx-file tx.json \\
      --script-group-type lock \\
      --cell-index 0 \\
      --bin ./target/riscv64imac-unknown-none-elf/debug/my-lock-script

    # Run with debug output enabled and increased cycle limit
    ckb-debugger \\
      --tx-file tx.json \\
      --script-group-type lock \\
      --cell-index 0 \\
      --bin ./build/debug/my-lock-script \\
      --max-cycles 70000000

  Transaction JSON format:
    The --tx-file expects a JSON file with the following structure:
    {
      "mock_info": {
        "inputs": [...],       // Input cells with their data and scripts
        "cell_deps": [...],    // Cell dependencies
        "header_deps": [...]   // Header dependencies (if any)
      },
      "tx": {
        "version": "0x0",
        "cell_deps": [...],
        "header_deps": [],
        "inputs": [...],
        "outputs": [...],
        "outputs_data": [...],
        "witnesses": [...]
      }
    }

  Reading the output:
    On success: The debugger prints the cycle count and exits with code 0.
      Run result: 0
      Total cycles consumed: 5234

    On failure: It prints the exit code and any debug output.
      Run result: 3
      (This means the script returned error code 3)

    With --enable-debug, ckb_debug! messages appear on stderr:
      DEBUG: fixed-lock: script execution started
      DEBUG: fixed-lock: loaded script args, length = 32
      DEBUG: fixed-lock: hash comparison FAILED
      Run result: 3
  `);
}

// ============================================================================
// Section 4: Reading Error Output from Failed Transactions
// ============================================================================

/**
 * When a transaction fails on the CKB node, the RPC returns an error
 * response with structured information about what went wrong.
 *
 * Here is what a typical error response looks like and how to interpret it.
 */
function printErrorOutputGuide(): void {
  console.log(`
  =====================================================================
  Reading Error Output from Failed Transactions
  =====================================================================

  When you submit a transaction to a CKB node and it fails script
  verification, you will receive an error response like this:

  Example RPC Error Response:
  {
    "code": -302,
    "message": "TransactionFailedToVerify: Verification failed Script(
      TransactionScriptError {
        source: Inputs[0].Lock,
        cause: script exit code: 3
      }
    )",
    "data": "Verification(Error { ... })"
  }

  Breaking this down:

  1. "code": -302
     This is the CKB RPC error code for "TransactionFailedToVerify".
     It means the transaction was well-formed but a script rejected it.

  2. "source": Inputs[0].Lock
     This tells you WHICH script failed:
       - Inputs[0]  = The first input cell (index 0)
       - .Lock      = The lock script of that cell
     Other possibilities:
       - Inputs[N].Type  = Type script of input N
       - Outputs[N].Type = Type script of output N

  3. "cause": script exit code: 3
     This is the exit code returned by your script.
     - Positive numbers (1, 2, 3, ...) = Your script returned this code
     - Negative numbers (-1, -2, ...) = CKB-VM returned this code
     - 0 would be success (but then you would not see this error!)

  Using the CCC SDK, you can catch and parse these errors:

    try {
      const txHash = await client.sendTransaction(tx);
    } catch (error) {
      // The error message contains the script source and exit code.
      // Parse it to identify which script failed and why.
      console.error("Transaction failed:", error.message);

      // Look for patterns like "Inputs[N].Lock" or "Inputs[N].Type"
      // and "exit code: N" to extract the relevant information.
    }

  Common RPC error codes:
    -301  TransactionFailedToResolve  (missing cell deps, inputs not found)
    -302  TransactionFailedToVerify   (a script returned non-zero exit code)
    -303  PoolRejectedDuplicatedTx    (transaction already in the pool)
    -304  PoolIsFull                  (transaction pool is at capacity)
    -311  PoolRejectedMalformedTx     (transaction structure is invalid)
  `);
}

// ============================================================================
// Section 5: Using ckb_debug! for Print Debugging
// ============================================================================

/**
 * The ckb_debug! macro is the primary way to add "print" debugging to
 * CKB scripts. Since scripts run in an isolated VM with no stdout,
 * ckb_debug! uses a special debug syscall that outputs messages when
 * the script runs under CKB-Debugger.
 *
 * In production (on the real CKB node), ckb_debug! calls are ignored
 * — they consume a small number of cycles but produce no visible output.
 */
function printDebugMacroGuide(): void {
  console.log(`
  =====================================================================
  Using ckb_debug! for Print Debugging
  =====================================================================

  The ckb_debug! macro is provided by the ckb-std crate and works like
  Rust's println! macro but outputs to the CKB-Debugger's stderr.

  Setup in Cargo.toml:
    [dependencies]
    ckb-std = "0.16"

  Usage in your script:
    use ckb_std::debug;

    pub fn program_entry() -> i8 {
        // Basic message
        debug!("script execution started");

        // With variables (supports format strings like println!)
        let args_len = args.len();
        debug!("args length: {}", args_len);

        // With hex data
        debug!("first 4 bytes of args: {:02x}{:02x}{:02x}{:02x}",
            args[0], args[1], args[2], args[3]);

        // Trace control flow
        if some_condition {
            debug!("taking the success path");
            return 0;
        }

        debug!("taking the error path");
        return 1;
    }

  Running with debug output:
    ckb-debugger \\
      --tx-file tx.json \\
      --script-group-type lock \\
      --cell-index 0 \\
      --bin ./build/debug/my-script

    Output:
      DEBUG: script execution started
      DEBUG: args length: 32
      DEBUG: first 4 bytes of args: a1b2c3d4
      DEBUG: taking the error path
      Run result: 1

  Tips for effective debug printing:
    1. Print at ENTRY and EXIT points of your script
    2. Print the LENGTH of all loaded data before using it
    3. Print the first few bytes of hashes for comparison
    4. Print which BRANCH the code takes at every if/match
    5. Print loop counters and iteration values
    6. Use a PREFIX in all messages (e.g., "my-lock: ...") so you can
       tell which script produced which output when multiple scripts run

  Performance note:
    - ckb_debug! calls consume a small number of VM cycles (~2000 per call)
    - In production, you may want to remove them or gate behind a feature flag
    - For development and testing, the overhead is negligible

  Conditional compilation (optional):
    #[cfg(debug_assertions)]
    debug!("this only compiles in debug mode");

    // Or use a feature flag:
    #[cfg(feature = "debug-output")]
    debug!("this only compiles when the feature is enabled");
  `);
}

// ============================================================================
// Section 6: The 4 Bugs in buggy-lock — Walkthrough
// ============================================================================

/**
 * Walks through each of the 4 bugs in the buggy-lock script, explaining
 * how they manifest, how to find them, and how to fix them.
 */
function printBugWalkthrough(): void {
  console.log(`
  =====================================================================
  Bug Walkthrough: The 4 Bugs in buggy-lock
  =====================================================================

  The buggy-lock script (contracts/buggy-lock/src/main.rs) implements a
  blake2b hash-based lock with 4 intentional bugs. Here is how to find
  and fix each one.

  ----- Bug #1: Off-by-one in args reading -----

  Location: Step 1, where expected_hash is extracted from args
  Buggy code:
    let expected_hash = &args[1..BLAKE2B_HASH_LEN + 1];
                             ^-- starts at 1 instead of 0

  Symptom:
    - The script reads bytes 1..33 instead of bytes 0..32
    - If args is exactly 32 bytes, this causes a runtime panic
      (index out of bounds), which shows up as a VM error
    - If args is longer, the script silently reads the wrong hash,
      causing ERROR_HASH_MISMATCH even with the correct preimage

  How to find it:
    - Add ckb_debug! to print the first few bytes of expected_hash
    - Compare with the hash you put in the args
    - The first byte will differ (shifted by one position)

  Fix:
    let expected_hash = &args[0..BLAKE2B_HASH_LEN];

  ----- Bug #2: Wrong witness index -----

  Location: Step 2, where the witness is loaded
  Buggy code:
    let witness = match load_witness(1, Source::Input) {
                                     ^-- index 1 instead of 0

  Symptom:
    - If the transaction has only 1 witness, this fails with
      INDEX_OUT_OF_BOUND (-1 VM error)
    - If there are multiple witnesses, it loads the WRONG witness,
      causing hash mismatch

  How to find it:
    - The error code will be -1 (INDEX_OUT_OF_BOUND) for single-witness txs
    - Add ckb_debug! before and after the load_witness call
    - The "after" message will never print if it fails

  Fix:
    let witness = match load_witness(0, Source::Input) {

  ----- Bug #3: Incorrect hash comparison length -----

  Location: Step 4, where computed_hash is compared to expected_hash
  Buggy code:
    let compare_len = 20; // Should be BLAKE2B_HASH_LEN (32)

  Symptom:
    - Only 20 of 32 bytes are compared
    - The script appears to work correctly in most tests because
      the first 20 bytes will differ for different preimages
    - This is a SECURITY vulnerability, not a functional bug in most cases
    - It reduces hash security from 256 bits to 160 bits

  How to find it:
    - This bug is subtle and may not show up in basic testing
    - Code review is the best way to catch it
    - A fuzzer that generates preimages with the same first 20 bytes
      but different remaining bytes would expose it

  Fix:
    let compare_len = BLAKE2B_HASH_LEN; // 32

  ----- Bug #4: Missing error code return -----

  Location: End of the function, after hash comparison fails
  Buggy code:
    debug!("buggy-lock: hash comparison FAILED");
    0 // This incorrectly returns success even when the hash doesn't match!

  Symptom:
    - The script ALWAYS returns 0 (success), even with the wrong preimage
    - This makes the lock script completely useless — anyone can spend
    - In testing, if you only test with the correct preimage, you will
      never notice this bug

  How to find it:
    - Test with an INCORRECT preimage — the script should fail but does not
    - Add ckb_debug! and notice that the FAILED message prints but the
      script still returns 0
    - This is why negative testing (testing failure cases) is critical

  Fix:
    ERROR_HASH_MISMATCH  // Return error code 3 instead of 0
  `);
}

// ============================================================================
// Section 7: Testing Strategies
// ============================================================================

/**
 * Outlines testing strategies that help prevent and catch the types of
 * bugs demonstrated in this lesson.
 */
function printTestingStrategies(): void {
  console.log(`
  =====================================================================
  Testing Strategies for CKB Scripts
  =====================================================================

  1. POSITIVE TESTS (Happy Path)
     - Provide correct inputs and verify the script returns 0
     - This catches obvious logic errors but misses security bugs
     - Example: hash lock with the correct preimage should succeed

  2. NEGATIVE TESTS (Error Paths)
     - Provide incorrect inputs and verify the script returns non-zero
     - This catches bugs like #4 (missing error return)
     - Example: hash lock with a wrong preimage should fail with code 3
     - Example: hash lock with an empty witness should fail with code 2

  3. BOUNDARY TESTS
     - Test with edge-case inputs: empty data, minimum length, maximum length
     - This catches bugs like #1 (off-by-one) and #3 (wrong length)
     - Example: args with exactly 32 bytes, args with 31 bytes, args with 33 bytes
     - Example: witness with 0 bytes, witness with 1 byte

  4. INDEX TESTS
     - Test with different numbers of inputs, outputs, and witnesses
     - This catches bugs like #2 (wrong witness index)
     - Example: transaction with 1 witness, 2 witnesses, 0 witnesses

  5. MOCK TRANSACTION TESTS
     - Use CKB-Debugger with crafted mock transactions
     - Each test is a JSON file with specific inputs that test one scenario
     - Run the script binary against each mock and check the exit code

  6. UNIT TESTS IN RUST
     - Test helper functions (like blake2b_hash) in isolation
     - Use #[cfg(test)] module with standard Rust test framework
     - Does not require CKB-VM — just tests pure logic

  7. INTEGRATION TESTS
     - Deploy the script to testnet and run real transactions
     - Tests the full end-to-end flow including molecule encoding
     - Catches issues with how the script interacts with the CKB protocol

  Test matrix for the hash lock script:
  +----------------------------+----------+------------------+
  | Test Case                  | Expected | Bug It Catches   |
  +----------------------------+----------+------------------+
  | Correct preimage           | Exit 0   | Basic logic      |
  | Wrong preimage             | Exit 3   | Bug #4 (missing) |
  | Empty witness              | Exit 2   | Error handling   |
  | No witness at all          | Exit -1  | Bug #2 (index)   |
  | Args exactly 32 bytes      | Exit 0   | Bug #1 (bounds)  |
  | Args exactly 31 bytes      | Exit 1   | Args validation  |
  | Preimage differs in last   | Exit 3   | Bug #3 (length)  |
  |   12 bytes only            |          |                  |
  +----------------------------+----------+------------------+
  `);
}

// ============================================================================
// Main: Run the complete debugging walkthrough
// ============================================================================

async function main(): Promise<void> {
  console.log("\n");
  console.log("  =============================================================");
  console.log("  Lesson 9: Debugging CKB Scripts");
  console.log("  =============================================================");
  console.log("\n  A comprehensive guide to finding and fixing bugs in CKB scripts.\n");

  // -----------------------------------------------------------------------
  // Part 1: Understanding CKB Error Codes
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Part 1: CKB-VM Error Codes");
  console.log("  =============================================================\n");

  console.log("  VM-level errors (returned by CKB-VM, always negative):\n");

  for (const [code, info] of Object.entries(VM_ERRORS)) {
    console.log(`  Exit Code ${code}: ${info.name}`);
    console.log(`    ${info.description}`);
    console.log(`    Common causes:`);
    for (const cause of info.commonCauses) {
      console.log(`      - ${cause}`);
    }
    console.log("");
  }

  console.log("\n  Well-known script error codes (from secp256k1-blake160):\n");

  for (const [code, info] of Object.entries(WELL_KNOWN_SCRIPT_ERRORS)) {
    console.log(`  Exit Code ${code}: ${info.name} (${info.script})`);
    console.log(`    ${info.description}`);
    console.log("");
  }

  // -----------------------------------------------------------------------
  // Part 2: Debugging Methodology
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Part 2: Debugging Methodology");
  console.log("  =============================================================\n");

  console.log("  The 5-step process for debugging CKB scripts:\n");
  console.log("    Step 1: READ THE ERROR");
  console.log("      - Identify the failing script (lock vs type, which input/output)");
  console.log("      - Note the exit code (VM error vs script error)");
  console.log("      - Check against known error code tables\n");
  console.log("    Step 2: REPRODUCE LOCALLY");
  console.log("      - Export the failing transaction to JSON");
  console.log("      - Run it through CKB-Debugger with the same script binary");
  console.log("      - Verify you get the same error locally\n");
  console.log("    Step 3: ADD DEBUG PRINTS");
  console.log("      - Insert ckb_debug!() at key decision points");
  console.log("      - Print lengths, indices, and hash prefixes");
  console.log("      - Trace the exact execution path\n");
  console.log("    Step 4: ISOLATE THE BUG");
  console.log("      - Narrow down to the specific line or operation");
  console.log("      - Check assumptions about data layout and encoding");
  console.log("      - Compare actual vs expected values from debug output\n");
  console.log("    Step 5: FIX AND VERIFY");
  console.log("      - Apply the fix and rerun under CKB-Debugger");
  console.log("      - Test both success AND failure cases");
  console.log("      - Deploy to testnet and test with real transactions\n");

  // -----------------------------------------------------------------------
  // Part 3: CKB-Debugger Command Reference
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Part 3: CKB-Debugger Usage");
  console.log("  =============================================================");

  printDebuggerUsage();

  // -----------------------------------------------------------------------
  // Part 4: Reading Error Output
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Part 4: Reading Error Output from Failed Transactions");
  console.log("  =============================================================");

  printErrorOutputGuide();

  // -----------------------------------------------------------------------
  // Part 5: ckb_debug! Macro
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Part 5: Using ckb_debug! for Print Debugging");
  console.log("  =============================================================");

  printDebugMacroGuide();

  // -----------------------------------------------------------------------
  // Part 6: Bug Walkthrough
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Part 6: The 4 Bugs in buggy-lock — Walkthrough");
  console.log("  =============================================================");

  printBugWalkthrough();

  // -----------------------------------------------------------------------
  // Part 7: Testing Strategies
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Part 7: Testing Strategies for CKB Scripts");
  console.log("  =============================================================");

  printTestingStrategies();

  // -----------------------------------------------------------------------
  // Summary
  // -----------------------------------------------------------------------

  console.log("  =============================================================");
  console.log("  Summary");
  console.log("  =============================================================\n");

  console.log("  In this lesson, you learned how to:\n");
  console.log("    1. Interpret CKB-VM error codes (negative) vs script error codes (positive)");
  console.log("    2. Follow a 5-step debugging methodology: Read -> Reproduce -> Debug -> Isolate -> Fix");
  console.log("    3. Use CKB-Debugger to run scripts locally against mock transactions");
  console.log("    4. Read and parse error output from failed transactions");
  console.log("    5. Add ckb_debug! print statements for tracing script execution");
  console.log("    6. Identify 4 common bug patterns: off-by-one, wrong index, wrong length, missing return");
  console.log("    7. Apply testing strategies that catch these bugs: positive, negative, boundary, and index tests\n");
  console.log("  Key takeaways:");
  console.log("    - Always test FAILURE cases, not just the happy path");
  console.log("    - CKB-Debugger is your best friend for local script development");
  console.log("    - Use distinct error codes for every failure mode in your scripts");
  console.log("    - ckb_debug! is low-cost and invaluable for tracing execution");
  console.log("    - Determinism is a feature: same inputs always produce the same result\n");
  console.log("  Next steps:");
  console.log("    - Try running the buggy-lock and fixed-lock scripts under CKB-Debugger");
  console.log("    - Run 'npx tsx src/error-guide.ts' for a complete error code reference");
  console.log("    - Move on to Lesson 10 to build a type script with state management\n");

  console.log("  =============================================================\n");
}

// ============================================================================
// Run the application
// ============================================================================

main().catch((error) => {
  console.error("\nFatal error:", error);
  process.exit(1);
});
